apiVersion: kuadra.kuadrant.io/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-sample
    app.kubernetes.io/part-of: kuadra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kuadra
  name: user-sample
spec:
  awsAccount:
    spec:
      user:
        userName: kuadra-test-1
        groups:
          - dns-management
  github:
    spec:
      username: your-github-username
      token: your-github-token
      organizations:
        - name: kuadrant
          teams:
            - name: engineering
              role: member
